// SecurityCspCard — renders a generated Content-Security-Policy as a real,
// portable artifact: copy the bare policy, copy it as a response header, or
// download a snippet file with nginx / Express examples. Generated from the
// origins the page actually loaded from, so it's a working starting point.

import { useState } from 'react';
import { copyToClipboard, downloadText, ArtifactCard } from './shared';

function snippetFile(host: string, policy: string): string {
  return [
    `# Content-Security-Policy generated by Chrome Buddy for ${host}`,
    '# Review every directive against your real needs before deploying.',
    '',
    `Content-Security-Policy: ${policy}`,
    '',
    '# --- nginx ---',
    `add_header Content-Security-Policy "${policy}" always;`,
    '',
    '# --- Express (helmet) ---',
    "// app.use(helmet.contentSecurityPolicy({ useDefaults: false, directives: { /* translate the policy above */ } }));",
    '',
  ].join('\n');
}

export function SecurityCspCard({
  policy,
  host,
  onDismiss,
}: {
  policy: string;
  host: string;
  onDismiss: () => void;
}) {
  const [copied, setCopied] = useState<string | null>(null);
  const flash = (k: string) => {
    setCopied(k);
    window.setTimeout(() => setCopied((c) => (c === k ? null : c)), 1400);
  };
  const copy = async (text: string, k: string) => {
    if (await copyToClipboard(text)) flash(k);
  };

  return (
    <ArtifactCard testid="ci-sec-csp" title="🛡️ Generated Content-Security-Policy" onDismiss={onDismiss}>
      <p className="ci-aia-hint">
          Built from the origins this page actually loaded. A starting point — review every directive (especially
          {' '}<code>script-src</code>) before deploying.
        </p>
        <pre className="ci-aia-code" data-testid="ci-sec-csp-policy">{policy}</pre>
        <div className="ci-panel-bar" style={{ borderBottom: 'none', padding: 0 }}>
          <button type="button" className="btn btn-sm btn-primary" onClick={() => copy(policy, 'policy')} data-testid="ci-sec-csp-copy">
            {copied === 'policy' ? 'Copied ✓' : 'Copy policy'}
          </button>
          <button type="button" className="btn btn-sm" onClick={() => copy(`Content-Security-Policy: ${policy}`, 'header')}>
            {copied === 'header' ? 'Copied ✓' : 'Copy as header'}
          </button>
          <button type="button" className="btn btn-sm" onClick={() => downloadText('content-security-policy.txt', snippetFile(host, policy))} data-testid="ci-sec-csp-download">
            Download
          </button>
        </div>
    </ArtifactCard>
  );
}
