// Pure helpers that turn enabled MCP server configs into the
// FunctionDeclaration list the agent runner ships to the model. Three jobs:
//
//   1. Filter: only servers with enabledInAgent === true contribute tools;
//      within a server, only tools whose toolFilter entry is absent-or-true
//      are included.
//   2. Namespace: tool names are emitted as `mcp_<serverId>_<toolName>` so
//      the dispatcher can route a call back to the right server.
//   3. Sanitize: tool descriptions are truncated to MAX_DESC_CHARS and
//      stripped of well-known prompt-injection patterns before joining the
//      prompt. JSON Schemas are passed through unchanged — sanitization of
//      additionalProperties / $schema is the model adapter's job (see
//      src/background/live.ts sanitizeForOpenApi).
//
// This module has NO chrome / no IDB / no network — call sites pass in the
// raw McpServer rows from the registry.

import type { McpServer } from './store';
import type { McpTool } from './protocol';

/** Cap on the tool description length sent to the model. ~200 chars is the
 *  sweet spot — long enough to convey purpose, short enough that 30 enabled
 *  tools cost ~6KB of context instead of ~60KB. Patterns longer than this
 *  are usually injection prose, not useful guidance. */
export const MAX_DESC_CHARS = 200;

/** Recognizable prompt-injection cues to strip from tool descriptions. Not a
 *  silver bullet — defense-in-depth alongside the HITL gate. Patterns are
 *  case-insensitive. */
const INJECTION_PATTERNS: RegExp[] = [
  /ignore\s+(all\s+)?previous\s+(instructions|system\s+prompt)/gi,
  /disregard\s+(the\s+)?(user|system|prior)/gi,
  /you\s+(must|should)\s+(immediately\s+)?(send|exfiltrate|leak)/gi,
  /system\s*:/gi, // pseudo-role tags that try to escalate
  /<\s*\/?\s*system\s*>/gi,
];

/** Shape we hand to the agent runner — a subset of Gemini's FunctionDeclaration. */
export interface FunctionDeclLite {
  name: string;
  description: string;
  parameters: Record<string, unknown>;
}

/** Tag attached to each declaration so the dispatcher can route. Kept separate
 *  from the function declaration itself (which goes straight to the model). */
export interface McpToolBinding {
  declaration: FunctionDeclLite;
  serverId: string;
  serverName: string;
  /** The ORIGINAL tool name on the server, before namespacing. */
  toolName: string;
  /** 'always' if the user has marked this (server,tool) pair as trusted. */
  trust: 'always' | 'confirm';
}

/** Separator between prefix / serverId / toolName in the namespaced form.
 *  Double underscore avoids ambiguity: server ids generated by genId() start
 *  with `mcp_` so single-underscore splitting would lose the boundary. */
const NS_SEP = '__';
const NS_PREFIX = `mcp${NS_SEP}`; // "mcp__"

/** Build the namespaced name we expose to the model. */
export function namespacedToolName(serverId: string, toolName: string): string {
  return `${NS_PREFIX}${serverId}${NS_SEP}${toolName}`;
}

/** Reverse: parse a namespaced name back into (serverId, toolName). Returns
 *  null when the name isn't in the namespaced shape. */
export function parseNamespacedToolName(
  name: string,
): { serverId: string; toolName: string } | null {
  if (!name.startsWith(NS_PREFIX)) return null;
  const rest = name.slice(NS_PREFIX.length);
  // Server ids generated by store.genId() contain a SINGLE underscore but no
  // double underscores. Splitting on the FIRST `__` gives us the right
  // boundary regardless of how the server id is shaped (defensive against
  // any future id scheme that uses underscores).
  const sep = rest.indexOf(NS_SEP);
  if (sep <= 0 || sep === rest.length - NS_SEP.length) return null;
  return { serverId: rest.slice(0, sep), toolName: rest.slice(sep + NS_SEP.length) };
}

/** Sanitize a description: strip injection-like phrases, normalize whitespace,
 *  truncate to MAX_DESC_CHARS with an ellipsis when needed. */
export function sanitizeDescription(raw: string | undefined): string {
  if (!raw) return '';
  let s = String(raw);
  for (const re of INJECTION_PATTERNS) s = s.replace(re, '[redacted]');
  s = s.replace(/\s+/g, ' ').trim();
  if (s.length > MAX_DESC_CHARS) {
    s = s.slice(0, MAX_DESC_CHARS - 1) + '…';
  }
  return s;
}

/** Drop a tool from the model's view? A tool is in iff:
 *   - the server is enabledInAgent
 *   - server.toolFilter[name] is absent OR true
 */
export function isToolEnabled(server: McpServer, toolName: string): boolean {
  if (!server.enabledInAgent) return false;
  const f = server.toolFilter ?? {};
  return f[toolName] !== false;
}

/** Top-level entry: walk all servers, emit one binding per enabled tool. */
export function collectMcpBindings(servers: McpServer[]): McpToolBinding[] {
  const bindings: McpToolBinding[] = [];
  for (const srv of servers) {
    if (!srv.enabledInAgent || !srv.tools) continue;
    for (const tool of srv.tools) {
      if (!isToolEnabled(srv, tool.name)) continue;
      bindings.push(bindOne(srv, tool));
    }
  }
  return bindings;
}

function bindOne(server: McpServer, tool: McpTool): McpToolBinding {
  return {
    declaration: {
      name: namespacedToolName(server.id, tool.name),
      description: sanitizeDescription(tool.description),
      parameters: tool.inputSchema && Object.keys(tool.inputSchema).length > 0
        ? tool.inputSchema
        : { type: 'object', properties: {} },
    },
    serverId: server.id,
    serverName: server.name,
    toolName: tool.name,
    trust: server.trust?.[tool.name] === 'always' ? 'always' : 'confirm',
  };
}
